### ISSUE TITLE
Diffusion equation

### ISSUE THREAD

**Issue by ainafp** [simulkade/FVTool#11]
Hello,

First of all, thank you for this tool! It is being very helpful.

I wanted to ask if there is any way I can input a tensor in D in the diffusion term, and if so how to do it.

Thanks!

**Comment by simulkade** [comment]
Hi @ainafp 

Thank you for your nice words.
Right now, you can only have the main diagonal of a tensor in the diffusion coefficient. For instance, for a 2D diffusion problem you can write:
```matlab
L = 50;  % domain length
Nx = 20; % number of cells
m = createMesh2D(Nx,Nx, L,L);
D_x = 1;
D_y = 20;
D = createFaceVariable(m, [D_x, D_y]);
Mdiff = diffusionTerm(D);
```
or alternatively
```matlab
L = 50;  % domain length
Nx = 20; % number of cells
m = createMesh2D(Nx,Nx, L,L);
D_x = 1;
D_y = 20;
D = createFaceVariable(m, 0.0);
D.xvalue(:) = D_x;
D.yvalue(:) = D_y;
Mdiff = diffusionTerm(D);
```

**Comment by simulkade** [comment]
@ainafp 
Apparently, it is possible to [diagonalize](https://en.wikipedia.org/wiki/Diagonalizable_matrix) the diffusion tensor by finding the [right coordinate](http://petrowiki.org/Diagonalizing_the_permeability_tensor).

**Comment by ainafp** [comment]
ok thanks! I'll try to do it diagonalizing and otherwise I will extend it to use a matrix.
Thank you for being so responsive! I saw you added the example to the toolbox too.

**Comment by simulkade** [comment]
Please feel free to submit a PR if you manage to extend the code. I forgot to link the example. It's good that you saw it yourself!

**Comment by ainafp** [comment]
Hello! 
I am trying to input the tensor finally, entering vectors instead of scalars in xvalue, yvalue and zvalue.
Can I do it as FaceVariable? Or should I do some kind of mean like harmonicMean?
I am not sure I understand the difference between face and center of the cells.
Thank you in advance!

**Comment by simulkade** [comment]
Hi @ainafp 
The fluxes are calculated on the interfaces between finite volume cells. Usually, the value of, e.g., concentration on the interface (or what I call a face variable) is calculated by linearly interpolating between the values of concentration in the neighboring cells. Also, the transport coefficients need to be calculated on the cell interfaces, that is done by using one of the averaging methods.  
To answer your question about using a FaceVariable or averaging an scalar to get the FaceVariable,  it depends on your specific problem. My guess is, you need to define the FaceVariable and assign the values of your diagonal tensors `[ax, ay, az]` to the FaceVariable, i.e.,
```
F = createFaceVariable(m, [ax, ay, az]);
```
which automatically assigns ax, ay, and az, to xvalue, yvalue, and zvalue of a FaceVariable, respectively.
