### ISSUE TITLE
solving reaction-diffusion(-advection) equations?

### ISSUE THREAD

**Issue by janelias1** [simulkade/FVTool#14]
Hello, 
Many thanks for this great piece of code. I am just wondering if it could be used also for reaction diffusion problems? like for the Fisher-KPP equation u_t = Laplacian(phi(u)) + u(1-u) where phi(u)=u^m. While I can solve  u_t = Laplacian(phi(u)) with FVTool, I don't know how to treat the nonlinear reaction term.  How about systems of nonlinear PDEs?
Thanks a lot!
Cheers,
Jan

**Comment by simulkade** [comment]
Hi @janelias1 

Yes , you can solve this equation by first linearizing the source term u(1-u) = u-u^2.
The first u is discretized as `M_s1 = linearSourceTerm(createCellVariablem, 1.0))`
The second term is linearized to
```
u^2 = u_0^2 + 2u_0(u-u_0) = 2u_0*u - u_0^2
```
which can be linearized as
```
RHS_s1 = constantSourceTerm(u_val.^2) % u_val is a cell variable containing the current value of u
M_s2 = linearSourceTerm(2*u_val)
```
Send me your code if it still does not work.

**Comment by janelias1** [comment]
Thanks a lot! I tried indeed to use this linearisation (Taylor expansion) before but with no success: I don't obtain any travelling wave solution of the Fisher-KPP equation. So I thought that the problem is with the reaction term. Can you please have a look at the code? I have just sent the code to your outlook.com email. Many thanks in advance.
