### ISSUE TITLE
Spherical coordinates not working

### ISSUE THREAD

**Issue by avaneeshnarla** [simulkade/FVTool#18]
I tried running the diffusiontutorial_spherical code, but I commented out line 20, and uncommented line 19 (switching BCs from left to right), and the computation no longer performs as expected. As I am just making a symmetric change in the BCs, is there a reason it doesn't work?

Thanks!

**Comment by simulkade** [comment]
Is the problem solved @avaneeshnarla ?

**Comment by avaneeshnarla** [comment]
Hi,

I guess the issue was more that I was confused as to what the boundary conditions mean in the Spherical, Cylindrical, Polar and Periodic cases. What does top/bottom mean when you are dealing with a circle? Is there any simple documentation I can go to? Right now, I have been trying to understand the definitions of the boundary conditions in each case.

**Comment by avaneeshnarla** [comment]
I think I figured it out. But also, I wanted to work in a radial geometry, but not have the annulus in the middle. Is there any way to avoid that?

**Comment by simulkade** [comment]
Sorry @avaneeshnarla for my late reply. Very busy these days with students.
I don't think you can have that. In fact, what you want to do cannot be done with a structured grid, and FVTool uses only structured grids.

**Comment by avaneeshnarla** [comment]
Hi Prof. Eftekhari,

No problem at all with the delay! I really appreciate your help. I realised the same after poring through the data structures. I decided to adapt your code and use conformal mappings to achieve the same.

Thanks!

**Comment by simulkade** [comment]
Hi @avaneeshnarla . Feel free to submit the PR if you like to add you code to FVTool. Let me know if you have difficulties going through the code.
