### ISSUE TITLE
Changing bounds of mesh

### ISSUE THREAD

**Issue by SA8416** [simulkade/FVTool#19]
Hi

Is it possible to change the bounds of a mesh? For instance in:
m = createMeshCylindrical2D(Nr, Nz, Lr, Lz)

Setting the values for Lr and Lz cause the mesh to extend from "0 to Lr" and "0 to Lz". Is it possible to change this so that the mesh extends from, say, "x to Lr" and "y to Lz" ? Thanks in advance!

**Comment by SA8416** [comment]
And to add, is there a way to extract the gradients of a distribution along with the distribution itself?

**Comment by simulkade** [comment]
Hi @SA8416 
It is possible to shift the origin:
```
m = createMeshCylindrical2D(Nr, Nz, Lr, Lz);
m.cellcenters.x=m.cellcenters.x+x0
m.facecenters.x=m.facecenters.x+x0
m.cellcenters.y=m.cellcenters.y+y0
m.facecenters.y=m.facecenters.y+y0
```
It is a bit cumbersome and ugly. I'll add a function to do it automatically.

I don't quite understand the second question. Do you want to get the gradient of a cell value? You can always use `gradientTerm` and `gradientCellTerm` functions.

**Comment by SA8416** [comment]
Thank you for the swift reply! I'd like to get the gradient at each face of a cell (north south east and west for 2D), including cells at the domain's boundaries.

**Comment by simulkade** [comment]
Then you should use gradientTerm function.
