### ISSUE TITLE
single phase flow and transport

### ISSUE THREAD

**Issue by ptrinka** [simulkade/FVTool#21]
Hi, very interesting suite of codes! I am looking for an example where both single flow and the ADE are solved but I haven't been able to find any. Is there any example that I could look at? Thanks in advance!

**Comment by simulkade** [comment]
Hi, could you provide an example, e.g, list of equations?

**Comment by ptrinka** [comment]
E.g. steady-state Richards equation and Advection-Dispersion equation.

**Comment by simulkade** [comment]
There is one example [here](https://github.com/simulkade/FVTool/blob/master/Examples/Tutorial/tracer_hetrogeneous.m). It is with Darcy's law, but you can probably convert it to Richards. Let me know if I can help.

**Comment by ptrinka** [comment]
Thanks a lot! That should work.
